baseURL = "http://gnbas.github.io/" # MI DIRECCIÓN DE SITIO GITHUB.IO
languageCode = "en-us"
title = "Gustavo Baselli - Proyectos y Trabajos"
themesDir = "./themes"
theme = "template-tallerproducto2021"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

summaryLength = 30

[[menu.main]]
    name = "Inicio"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Documentación"
    url = "/docs/"
    weight = 2

[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Ir a Documentación'
  homepage_intro = 'Repositorio Taller de Producto Universidad Adolfo Ibáñez 2021'
  homepage_image = '/images/bg-home.png'


  [params.homepage_meta_tags]
    meta_description = "Repositorio Taller de Producto Universidad Adolfo Ibáñez 2021"
    meta_og_title = "Gustavo Baselli"
    meta_og_type = "website"
    meta_og_url = ""
    meta_og_image = ""
    meta_og_description = "Repositorio Taller de Producto Universidad Adolfo Ibáñez 2021"
    meta_twitter_card = "summary"
    meta_twitter_site = "@lab_uai"
    meta_twitter_creator = "@lab_uai"

  [params.logo]
      mobile = "/images/logo-uai.png"
      standard  = "/images/logo-uai.png"
